---
title: 'modComp study causal attribution task: psychoeducation intervention pilot data '
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    html-math-method:
      method: mathjax
  #  pdf_document:
  # extra_dependencies: ["bbm"]
  # fig_caption: yes
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo=FALSE, error=TRUE, warning=FALSE, message=FALSE, fig.align='center')

# load packages
packages <- c("rjson", "dplyr", "tidyverse", "tidyr", "reshape2", "ggpmisc", 
              "patchwork", "devtools", "wesanderson", "unikn", "summarytools",
              "lme4", "lmerTest", "subscore", "emmeans", "rstatix", "jtools")
if (length(setdiff(packages, rownames(installed.packages()))) > 0 ) {
  install.packages(setdiff(packages, rownames(installed.packages())), repos = "http://cran.us.r-project.org")
}
lapply(packages, require, character.only=TRUE)

# load rainCloudPlot src code
source_url("https://raw.githubusercontent.com/RainCloudPlots/RainCloudPlots/master/tutorial_R/R_rainclouds.R")

# set wd
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# create figures subdir
subdir <- "figures"
if (!file.exists(subdir)){
  dir.create(file.path(dirname(rstudioapi::getActiveDocumentContext()$path), subdir))
}
```

```{r specify_task}
## set-up where to look for data, and what task version to get
# where firebase raw output files have been downloaded to
data_dir <- "../data"
# what task version to filter for
task_ver <- "causal-attr-pe-1"         #"causal-attr-pe-2"
```

```{r setup_colour_scales}
# lets set some custom colour scales for our plots using unikn
#seecol(pal_unikn_pair)
palette2 <- usecol(pal_unikn_pair)
# colours by intervention group
colours3 <- c(#"planning" = palette2[11],
              #"control" = palette2[10],             # planning control
              "psychoeducation" = palette2[2],
              "control" = palette2[3]                # psychoed control
              )
# colours by model parameter type
colours2 <- c("group mean" = palette2[14],
              "intervention effect" = palette2[2],
              "baseline effect" = palette2[4]
              )
```

```{r setup_data_proc_functions}
# function to read all task data files in input list from json to nice df
read_ca_choice_json <- function(file) {
  # read file from json into an R list:
  data_f <- rjson::fromJSON(file = file, simplify = TRUE)

  # select only trial data (numbered list items)
  data_f_task <- data_f[grepl("^choiceTask.*.[[:digit:]]", names(data_f))]
  
  # convert to tibble to easily un-nesting of list data
  data_tib <- tibble(data_f_task)  %>% 
    mutate(variable = names(data_f_task)) %>%
    unnest_wider(data_f_task) #%>%
    # unnest_wider(choices) %>%
    # rename("attr1"=`...1`,
    #        "attr2"=`...2`,
    #        "attr3"=`...3`,
    #        "attr4"=`...4`)
    
  # and finally convert to a df with all the other info we want:
  data_df <- as.data.frame(data_tib) %>%
    separate(variable, into=c("tmp", "tmp2"), sep="k") %>%
    separate(tmp2, into=c("taskNo", "trialNo")) %>%
    dplyr::select(-tmp) %>%
    arrange(trialNo) %>%
    mutate(subID = data_f$prolificSubID,
           studyID = data_f$prolificStudyID,
           firebaseID = data_f$firebaseUID,
           condition = data_f$condition,
           taskVer = task_ver,
           totalTimeJsPsych = data_f$totalTimeJsPsych,
           intStartTime = data_f$interventionStartTime,
           intEndTime = data_f$interventionEndTime
           ) 
}

# function to read all task data files in input list from json to nice df
read_ca_learning_json <- function(file) {
  # read file from json into an R list:
  data_f <- rjson::fromJSON(file = file, simplify = TRUE)

  # select only trial data (numbered list items)
  data_f_task <- data_f[grepl("^learningTask.*.[[:digit:]]", names(data_f))]
  
  # convert to tibble to easily un-nesting of list data
  data_tib <- tibble(data_f_task)  %>% 
    unnest_wider(data_f_task)
    
  # and finally convert to a df with all the other info we want:
  data_df <- as.data.frame(data_tib) %>%
    arrange(trialNo) %>%
    mutate(subID = data_f$prolificSubID,
           studyID = data_f$prolificStudyID,
           firebaseID = data_f$firebaseUID,
           condition = data_f$condition,
           taskVer = task_ver,
           totalTimeJsPsych = data_f$totalTimeJsPsych,
           intStartTime = data_f$interventionStartTime,
           intEndTime = data_f$interventionEndTime
           ) 
}

# function to read all files in input list from json to nice df
read_quest_json <- function(file) {
  # read file from json into an R list:
  data_f <- rjson::fromJSON(file = file, simplify = TRUE)
  # select only trial data (numbered list items)
  data_f_quest <- data_f[lengths(data_f)>1]
  data_f_quest <- data_f_quest[!grepl("rating", names(data_f_quest))]
  data_f_quest <- data_f_quest[!grepl("freeText", names(data_f_quest))]
  data_f_quest <- data_f_quest[!grepl("PHQstate", names(data_f_quest))]
  data_f_quest <- data_f_quest[!grepl("intervention", names(data_f_quest))]
  
  # convert to tibble to easily un-nesting of list data
  data_tib <- tibble(data_f_quest) %>%
    unnest_longer(data_f_quest)
  
  # and finally convert to a df with all the other info we want:
  data_df <- as.data.frame(data_tib) %>%
    rename("answer" = "data_f_quest",
           "quest" = "data_f_quest_id") %>%
    mutate(subID = data_f$prolificSubID)
}

# function to read all files in input list from json to nice df
read_int_json <- function(file) {
  # read file from json into an R list:
  data_f <- rjson::fromJSON(file = file, simplify = TRUE)
  # select only phqstate data
  data_f_i <- data_f[grepl("intervention", names(data_f))]
  data_f_i <- data_f_p[!grepl("RT", names(data_f_i))]
  
  # convert to tibble to easily un-nesting of list data
  data_tib <- tibble(data_f_i) %>%
    mutate(variable = names(data_f_i)) %>%
    unnest_wider(data_f_i)
  
  # and finally convert to a df with all the other info we want:
  data_df <- as.data.frame(data_tib) %>%
    mutate(subID = data_f$prolificSubID)
}

# function to read all files in input list from json to nice df
read_phqs_json <- function(file) {
  # read file from json into an R list:
  data_f <- rjson::fromJSON(file = file, simplify = TRUE)
  # select only phqstate data
  data_f_p <- data_f[grepl("PHQstate", names(data_f))]
  data_f_p <- data_f_p[!grepl("RT", names(data_f_p))]
  
  # convert to tibble to easily un-nesting of list data
  data_tib <- tibble(data_f_p) %>%
    mutate(variable = names(data_f_p)) %>%
    unnest_wider(data_f_p)
  
  # and finally convert to a df with all the other info we want:
  data_df <- as.data.frame(data_tib) %>%
    mutate(subID = data_f$prolificSubID)
}

# function to read all files in input list from json to nice df
read_freetxt_json <- function(file) {
  # read file from json into an R list:
  data_f <- rjson::fromJSON(file = file, simplify = TRUE)
  # select only trial data (numbered list items)
  data_f_ft <- data_f[grepl("freeText", names(data_f))]
  data_f_ft <- data_f_ft[!grepl("RT", names(data_f_ft))]
  
  # convert to tibble to easily un-nesting of list data
  data_tib <- tibble(data_f_ft) %>%
    mutate(variable = names(data_f_ft)) %>%
    unnest_wider(data_f_ft)
  
  # and finally convert to a df with all the other info we want:
  data_df <- as.data.frame(data_tib) %>%
    mutate(subID = data_f$prolificSubID)
}

# function to read all files in input list from json to nice df
read_ratings_json <- function(file) {
  # read file from json into an R list:
  data_f <- rjson::fromJSON(file = file, simplify = TRUE)
  # select only trial data (numbered list items)
  data_f_r <- data_f[grepl("ratings", names(data_f))]
  data_f_ro <- data_f_r[!grepl("RT", names(data_f_r))]
  data_f_rt <- data_f_r[grepl("RT", names(data_f_r))]
  
  # convert to tibble to easily un-nesting of list data
  data_tib <- tibble(data_f_ro) %>%
    mutate(variable = names(data_f_ro)) %>%
    unnest_wider(data_f_ro) %>%
    rename("ext_int"=`...1`,
           "spec_glob"=`...2`)
  
  # and finally convert to a df with all the other info we want:
  data_df <- as.data.frame(data_tib) %>%
    mutate(subID = data_f$prolificSubID)
}
```

```{r load_choice_data}
# ## load all the existing data files
# # get list of individual ppt files (main task data files only)
# data_files <- list.files(path = data_dir,
#                          pattern = paste0("^", task_ver, ".*data.txt$"),
#                          full.names = TRUE)
# 
# # apply preproc functions to get the data in a nice df format
# data_all_choice <- lapply(data_files, read_ca_choice_json)       # returns nested list of processed data
# data_long_choice <- do.call(rbind, data_all_choice)              # binds all list elements into one big df
# 
# # save a copy
# data_long_choice <- data_long_choice %>%
#   select(-choices) %>%
#   arrange(subID, taskNo, trialNo)
# write.csv(data_long_choice, file=paste0(task_ver, "-choice-task-data-long.csv"))
# 
# ## get the number of participants and number of trials per participant in the current dataset
# nPpts <- length(unique(data_long_choice$subID))  # get number of participants
# nTrials_all <- data_long_choice %>%              # get number of trials each participant actually completed
#   group_by(subID) %>%
#   summarize(nTrials = n()) %>%
#   mutate(ID=seq(1, nPpts, 1))                     # assign sequential numeric subIDs for ease / anonymity
# data_long_choice <- merge(data_long_choice, nTrials_all, by="subID")

# OR load pre-processed data 
data_long_choice <- read.csv(file=paste0(task_ver, "-choice-task-data-long.csv"))
nPpts <- length(unique(data_long_choice$subID))
nTrials_max_choice <- 64

# and get lists of subjects by condition for use with other data
control_subs <- data_long_choice %>%
  filter(condition=="control") %>%
  dplyr::select(subID)
controls <- as.list(unique(control_subs$subID))

active_subs <- data_long_choice %>%
  filter(condition=="psychoed") %>%
   dplyr::select(subID)
actives <- as.list(unique(active_subs$subID))
```

Participants so far for task version `r task_ver` (*N*=`r nPpts`):

```{r prolific_QC_bonus}
# get basic quality control data and determine prolific bonuses
QC_bonus_ch <- data_long_choice %>% 
  arrange(subID, itemNo) %>% 
  group_by(subID, taskNo) %>%
  summarize(nTrials = n(),
            medianRT = round(median(rt, na.rm=T)/1000,1),
            prop1 = round(sum(response==1, na.rm=T)/(nTrials_max_choice), 2),
            condition = condition[1],
            intTime = round((intEndTime[1] - intStartTime[1])/60000,2),
            )
knitr::kable(QC_bonus_ch,
             caption = paste(task_ver, "choice task data"))

# N's per cond
N_cond <- QC_bonus_ch %>%
  group_by(condition, taskNo) %>%
  summarise(N=n())
knitr::kable(N_cond)
```

### Overall QC

```{r qc_plots}
qc_p <- QC_bonus_ch %>%
  mutate(dataCompleteness = nTrials/nTrials_max_choice) %>%
  melt(id.vars=c("condition")) %>%
  filter(variable == "dataCompleteness" | variable == "prop1") %>%
  group_by(condition, variable) %>%
  summarise(mean = mean(as.numeric(value), na.rm=TRUE),
            sd = sd(value)) %>%
  ggplot(aes(x=variable, y=mean, fill=condition, group=condition)) +
  geom_bar(stat="Identity", position=position_dodge2(0.8)) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), position = position_dodge2(width=0.4, padding=0.4)) +
  theme_minimal() + ylab("") + 
  scale_fill_manual(values=wes_palette(n=4, name="Darjeeling1"))
qc_p
```

```{r load_scenario_info}
# # ! don't need to re-run if using preprocessed csv data files, including for reference
# # load my coding of the scenario (stimulus) properties
# event_info <- read.csv("event_coding.csv") %>%
#   rename(itemNo = item) %>%
#   mutate(itemNo = itemNo-1)
# 
# # and merge into main file for future analysis
# data_long_choice <- merge(data_long_choice, event_info, by=c("itemNo", "valence"), no.dups=TRUE) %>%
#   arrange(subID, taskNo, trialNo)
# 
```

```{r choice_derivs}
# # ! don't need to re-run if using preprocessed csv data files, including for reference
# # add some basic derivatives to the data
# data_long_choice <- data_long_choice %>%
#     mutate(
#            internalChosen = ifelse((grepl("internal",chosen_attr_type)), 1, 0),
#            globalChosen = ifelse((grepl("global",chosen_attr_type)), 1, 0),
#            internalGlobalChosen = ifelse((grepl("internal_global",chosen_attr_type)), 1, 0),
#            internalSpecificChosen = ifelse((grepl("internal_specific",chosen_attr_type)), 1, 0),
#            externalGlobalChosen = ifelse((grepl("external_global",chosen_attr_type)), 1, 0),
#            externalSpecificChosen = ifelse((grepl("external_specific",chosen_attr_type)), 1, 0)) %>%
#   group_by(subID)
# # re-save for convenience
# write.csv(data_long_choice, file=paste0(task_ver, "-choice-task-data-long.csv"))
```

### Overall proportionate choice: evidence of self-serving bias?

At the group level, do we see evidence for self-serving bias? Is this affected by task no or intervention?

```{r prop_choice_by_type}
# plot by attribution choices and valence
rp1 <- data_long_choice %>%
  mutate(condition = ifelse(condition=="psychoed", "psychoeducation", "control")) %>%
  dplyr::select(subID, valence, taskNo, condition, internalChosen) %>%
  melt(id.vars=c("subID", "valence", "taskNo", "condition")) %>%
  mutate(taskNo = as.factor(taskNo)) %>%
  group_by(subID, valence, taskNo, condition) %>%
  summarise(mean_internal = mean(value)) %>%
  ggplot(aes(x=taskNo, y=mean_internal, group=interaction(condition, taskNo), 
             colour=condition, fill=condition)) +
  geom_flat_violin(position=position_nudge(x = .1, y = 0),  
                   adjust = 1.5, trim = TRUE, alpha = .4, colour = NA) +
  geom_point(position=position_jitter(width=.02), size = 3, shape = 20) +
  geom_line(aes(group=subID, colour=condition), alpha = .4) +
  geom_boxplot(outlier.shape = NA, alpha = .6, width = .3, colour = "black") +
  theme_minimal() + facet_wrap(~valence) +
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  labs(x="task no", y="proportion internal attributions") +
  theme(legend.title = element_blank()) + theme(legend.position="top")

rp2 <- data_long_choice %>%
  mutate(condition = ifelse(condition=="psychoed", "psychoeducation", "control")) %>%
  dplyr::select(subID, valence, taskNo, condition, globalChosen) %>%
  melt(id.vars=c("subID", "valence", "taskNo", "condition")) %>%
  mutate(taskNo = as.factor(taskNo)) %>%
  group_by(subID, valence, taskNo, condition) %>%
  summarise(mean_internal = mean(value)) %>%
  ggplot(aes(x=taskNo, y=mean_internal, group=interaction(condition, taskNo), 
             colour=condition, fill=condition)) +
  geom_flat_violin(position=position_nudge(x = .1, y = 0),  
                   adjust = 1.5, trim = TRUE, alpha = .4, colour = NA) +
  geom_point(position=position_jitter(width=.02), size = 3, shape = 20) +
  geom_line(aes(group=subID, colour=condition), alpha = .4) +
  geom_boxplot(outlier.shape = NA, alpha = .6, width = .3, colour = "black") +
  theme_minimal() + facet_wrap(~valence) +
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  labs(x="task no", y="proportion global attributions") +
  theme(legend.title = element_blank()) + theme(legend.position="top")

(rp1 + rp2)
```

```{r basic_stats}
# linear mixed models
lme1 <- lmer(internalChosen ~ valence * condition * taskNo +  ( 1 | subID ),
            data=data_long_choice)
summary(lme1)
anova(lme1)
emmeans(lme1, list(pairwise ~ condition*valence*taskNo), adjust = "tukey", pbkrtest.limit = 6400)


lme1 <- lmer(globalChosen ~ valence * condition * taskNo +  ( 1 | subID ),
            data=data_long_choice)
summary(lme1)
anova(lme1)
emmeans(lme1, list(pairwise ~ condition*valence*taskNo), adjust = "tukey", pbkrtest.limit = 6400)
```

### Choice RT data

```{r choice_rt}
p <- data_long_choice %>%
  dplyr::select(subID, valence, trialNo, taskNo, condition, rt) %>%
  group_by(subID, taskNo, valence) %>%
  mutate(trialNoByVal = 1:n()) %>%
  ggplot(aes(x=trialNoByVal, y=rt/6000, group=valence, colour=valence, fill=valence)) +
  stat_summary(fun=mean, geom="line") +
  stat_summary(fun.data=mean_se, geom="ribbon", alpha=.2, 
                   colour = NA) +
  ylab("mean RT") +
  xlab("trial") + facet_grid(cols=vars(taskNo), rows=vars(condition)) +
  theme_minimal() + theme(legend.position="top") + ylim(0,5) +
  scale_fill_manual(values=wes_palette(n=2, name="Darjeeling1")) 
p

p <- data_long_choice %>%
  dplyr::select(subID, valence, trialNo, taskNo, condition, rt) %>%
  group_by(subID, taskNo, valence) %>%
  mutate(trialNoByVal = 1:n()) %>%
  ggplot(aes(x=trialNoByVal, y=rt/6000, group=valence, colour=valence, fill=valence)) +
  stat_summary(fun=median, geom="line") +
  stat_summary(fun.data=median_hilow, geom="ribbon", alpha=.2, 
                   colour = NA) +
  ylab("median RT") +
  xlab("trial") + facet_grid(cols=vars(taskNo), rows=vars(condition)) +
  theme_minimal() + theme(legend.position="top") + ylim(0,10) +
  scale_fill_manual(values=wes_palette(n=2, name="Darjeeling1")) 
p

# linear mixed model
lme1 <- lmer(rt ~ valence * condition * taskNo + (1 | subID:taskNo), data=data_long_choice)
summary(lme1)
anova(lme1)
```


### Intervention data

```{r int_time}
p1 <- QC_bonus_ch %>%
  mutate(condition = ifelse(condition=="psychoed", "psychoeducation", "control")) %>%
  ggplot(aes(x=intTime, group=condition, fill=condition)) +
  geom_histogram(alpha=.6, position = "identity", binwidth = 1) + #
  theme_minimal() + theme(legend.position = "right") +
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  xlab("time spent on intervention (mins)") + xlim(0,20)
p1

data_aov <- QC_bonus_ch %>%
  dplyr::select(subID, condition, intTime) %>%
  group_by(subID, condition) %>%
  summarise(mean_int_time = mean(intTime)) %>%
  ungroup
res.aov <- anova_test(data = data_aov, dv = mean_int_time, wid = subID, between=condition)
get_anova_table(res.aov)
```

### Self-report data

Who were our participants?

```{r load_selfreports}
# # apply preproc functions to get the data in a nice df format
# data_quest_all <- lapply(quest_data_files, read_quest_json)   # returns nested list of processed data
# data_quest_long <- do.call(rbind, data_quest_all)             # binds all list elements into one big df
# data_quest_wide <- pivot_wider(data_quest_long, id_cols = subID, names_from = quest,
#                                values_from = answer) %>%
#   dplyr::select(-P0_Q0, -study_feedback) %>%
#   mutate(demogs_age = replace(demogs_age, subID=="5ed7a0239e6b4a23ec6eb236", 21),
#          demogs_gender = replace(demogs_gender, subID=="5ed7a0239e6b4a23ec6eb236", "man")) %>%
#   # fix list data identified using sapply(data_quest_wide, class) so can save as csv
#   mutate(across(c(is.list, -contains("demogs"), -contains("catch_2"),
#                   -contains("study_acceptability")),
#                 as.numeric),
#          demogs_age = as.numeric(demogs_age),
#          across(c(is.list),
#                 as.character))
#
# #save a copy
# write.csv(data_quest_wide, file=paste0(task_ver, "-self-report-data.csv"))

# OR load data
data_quest_wide <- read.csv(file=paste0(task_ver, "-self-report-data.csv")) %>%
  dplyr::select(-X)
```

```{r table_demogs}
summ <- data_quest_wide %>%
  mutate(prevPsychTx = ifelse(grepl("yes", demogs_tx), "yes", 
                              ifelse(demogs_tx=="prefer not to say", "prefer not to say", "no")),
         tx_talkingTher = ifelse(grepl("talking therapy", demogs_tx), "yes", "no"),
         tx_meds = ifelse(grepl("medication", demogs_tx), "yes", "no"),
         tx_selfGuided = ifelse(grepl("self-guided", demogs_tx), "yes", "no"),
         tx_other = ifelse(grepl("other", demogs_tx), "yes", "no")) %>%
  dplyr::select(demogs_age,
                demogs_gender,
                demogs_employment,
                demogs_financial,
                demogs_housing,
                demogs_neurodiv,
                prevPsychTx,
                tx_talkingTher,
                tx_meds,
                tx_selfGuided,
                tx_other,
                PHQ9_total,
                DAS_total,
                miniSPIN_total)

view(dfSummary(summ))
```


```{r plot_demogs}
p1 <- data_quest_wide %>%
  filter(!subID=="5ed7a0239e6b4a23ec6eb236") %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation")) %>%
  ggplot(aes(x=demogs_age, fill=group, group=group)) +
  geom_histogram(alpha=.6, position = "identity") + #, binwidth=5
  theme_minimal() + theme(legend.position = "none") +
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  xlab("age")
#p1

p2 <- data_quest_wide %>%
  filter(!subID=="5ed7a0239e6b4a23ec6eb236") %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation")) %>%
  ggplot(aes(x=demogs_gender, fill=group, group=group)) +
  geom_bar(aes(y=..prop..), alpha=.6, position = "dodge") + 
  theme_minimal() + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust=1.1, hjust=1)) +
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  xlab("gender identity")
#p2  

p3 <- data_quest_wide %>%
  filter(!subID=="5ed7a0239e6b4a23ec6eb236") %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation")) %>%
  ggplot(aes(x=demogs_housing, fill=group, group=group)) +
  geom_bar(aes(y=..prop..), alpha=.6, position = "dodge") + 
  scale_x_discrete(labels=c("homeowner", "tenant", "other")) +
  theme_minimal() + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust=1.1, hjust=1)) +
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  xlab("housing status")
#p3  

p4 <- data_quest_wide %>%
  filter(!subID=="5ed7a0239e6b4a23ec6eb236") %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation")) %>%
  ggplot(aes(x=demogs_employment, fill=group, group=group)) +
  geom_bar(aes(y=..prop..), alpha=.6, position = "dodge") + 
  scale_x_discrete(labels=c("employed", "not seeking", "unemployed")) +
  theme_minimal() + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust=1.1, hjust=1)) +
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  xlab("employment status")
#p4 

p5 <- data_quest_wide %>%
  filter(!subID=="5ed7a0239e6b4a23ec6eb236") %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation")) %>%
  ggplot(aes(x=demogs_financial, fill=group, group=group)) +
  geom_bar(aes(y=..prop..), alpha=.6, position = "dodge") + 
  scale_x_discrete(labels=c("doing OK", "just getting by", "struggling")) +
  theme_minimal() + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust=1.1, hjust=1)) +
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  xlab("financial status")
#p5

p6 <- data_quest_wide %>%
  filter(!subID=="5ed7a0239e6b4a23ec6eb236") %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation")) %>%
  ggplot(aes(x=study_acceptability, fill=group, group=group)) +
  geom_bar(aes(y=..prop..), alpha=.6, position = "dodge") + 
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  theme_minimal() + xlab("task acceptability")
#p6

((p1 + p2 + p3) / (p4 + p5 + p6))

p7 <- data_quest_wide %>%
  filter(!subID=="5ed7a0239e6b4a23ec6eb236") %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation")) %>%
  ggplot(aes(x=demogs_neurodiv, fill=group, group=group)) +
  geom_bar(aes(y=..prop..), alpha=.6, position = "dodge") + 
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  theme_minimal() + xlab("self-reported neurodiversity") + theme(legend.position="none")
#p7

p8 <- data_quest_wide %>%
  filter(!subID=="5ed7a0239e6b4a23ec6eb236") %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation"),
         prevPsychTx = ifelse(grepl("yes", demogs_tx), "yes", 
                              ifelse(demogs_tx=="prefer not to say", "prefer not to say", "no"))) %>%
  ggplot(aes(x=prevPsychTx, fill=group, group=group)) +
  geom_bar(aes(y=..prop..), alpha=.6, position = "dodge") + 
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  theme_minimal() + xlab("previous tx for a mental health problem")
#p7

(p7 + p8)

p9 <- data_quest_wide %>%
  filter(!subID=="5ed7a0239e6b4a23ec6eb236") %>%
  mutate(condition = ifelse((subID %in% controls), "control", "psychoeducation"),
         tx_talkingTher = ifelse(grepl("talking therapy", demogs_tx), "yes", "no"),
         tx_meds = ifelse(grepl("medication", demogs_tx), "yes", "no"),
         tx_selfGuided = ifelse(grepl("self-guided", demogs_tx), "yes", "no"),
         tx_other = ifelse(grepl("other", demogs_tx), "yes", "no")) %>%
  dplyr::select(subID, condition, contains("tx"), -demogs_tx) %>%
  melt(id.vars=c("subID", "condition")) %>%
  ggplot(aes(x=variable, fill=value, group=interaction(variable, value))) +
  geom_bar(alpha=.6, position = "dodge") + 
  theme_minimal() + xlab("") +
  scale_x_discrete(labels=c("talking therapy", "medication", "self-guided", "other"))
p9 <- p9 + facet_wrap(~condition)
p9

p10 <- data_quest_wide %>%
  filter(!subID=="5ed7a0239e6b4a23ec6eb236") %>%
  mutate(dis_concentrate = ifelse(grepl("concentrate", demogs_disability), "yes", "no"),
         dis_people = ifelse(grepl("people", demogs_disability), "yes", "no"),
         dis_physEff = ifelse(grepl("physical effort", demogs_disability), "yes", "no"),
         dis_rrm = ifelse(grepl("maths", demogs_disability), "yes", "no"),
         dis_other = ifelse(grepl("other", demogs_disability), "yes", "no")) %>%
  dplyr::select(subID, contains("dis"), -demogs_disability) %>%
  melt(id.vars=c("subID")) %>%
  ggplot(aes(x=variable, fill=value, group=interaction(variable, value))) +
  geom_bar(alpha=.6, position = "dodge") +
  theme_minimal() + xlab("type of functional disability") +
  scale_x_discrete(labels=c("concentrating\n for long periods", 
                            "dealing with people\nyou don't know", 
                            "activities requiring\nphysical effort", 
                            "reading, writing, \nor maths", 
                            "other form\nof impairment")) +
  theme(axis.text.x = element_text(angle = 45, vjust=1.1, hjust=1)) +
  scale_fill_manual(values=wes_palette(n=2, name="GrandBudapest1"))
p10
```

```{r score_selfreports}
# # ! don't need to re-run if loading pre-processed csv data, including for reference
# # catch questions
# tmp <- data_quest_wide %>%
#   dplyr::select(contains("catch_"), subID) %>%
#   mutate(catchQcorr1 = ifelse(catch_1>=2, 1, 0),
#          catchQcorr2 = ifelse(catch_2=="yes", 1, 0),
#          catchQscorr = catchQcorr1 + catchQcorr2,
#          catchQsCorrect = ifelse(catchQscorr==2, "yes", "no")) %>%
#   dplyr::select(subID, catchQsCorrect)
# data_quest_wide <- merge(data_quest_wide, tmp, by = "subID")
#
# # PHQ9
# PHQ9 <- data_quest_wide[, grep(pattern ='^PHQ9_.*', names(data_quest_wide))]  %>%
#   dplyr::select(sort(tidyselect::peek_vars()))  # rearrange to alphabetical/numeric order
# data_quest_wide$PHQ9_total <- rowSums(PHQ9[1:9])
# 
# # miniSPIN
# miniSPIN <- data_quest_wide[, grep(pattern ='^miniSPIN_.*', names(data_quest_wide))]  %>%
#   dplyr::select(sort(tidyselect::peek_vars()))
# data_quest_wide$miniSPIN_total <- rowSums(miniSPIN)
# 
# # DAS-SF
# DAS <- data_quest_wide[, grep(pattern ='^DAS_.*', names(data_quest_wide))]  %>%
#   dplyr::select(sort(tidyselect::peek_vars())) %>%
#   mutate(across(is.numeric,
#                ~recode(., `0`=4,`1`=3,`2`=2,`3`=1))) # all items are reverse scored
# data_quest_wide$DAS_total <- rowSums(DAS)
# 
# # save a copy
# write.csv(data_quest_wide, file=paste0(task_ver, "-self-report-data.csv"))
```

```{r plot_selfreports}
p1 <- data_quest_wide %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation")) %>%
  ggplot(aes(x=PHQ9_total, fill=group, group=group)) +
  geom_histogram(alpha=.6, position = "identity") + 
  theme_minimal() + theme(legend.position = "none") +
  geom_vline(xintercept = 10, linetype = "dashed") +  # rough cutoff for clinical depression
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  xlab("PHQ9 total")

p3 <- data_quest_wide %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation")) %>%
  ggplot(aes(x=miniSPIN_total, fill=group, group=group)) +
  geom_histogram(alpha=.6, position = "identity") + 
  theme_minimal() + theme(legend.position = "none") +
  geom_vline(xintercept = 6, linetype = "dashed") +  # rough cutoff for significant social phobia
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  xlab("miniSPIN total")

p2 <- data_quest_wide %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation")) %>%
  ggplot(aes(x=DAS_total, fill=group, group=group)) +
  geom_histogram(alpha=.6, position = "identity") + 
  theme_minimal() + theme(legend.position = "none") +
  geom_vline(xintercept = 23.8, linetype = "dashed", colour="dark grey") +  # mean score in dpressed inpatients
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  xlab("DAS-SF total")

p4 <- data_quest_wide %>%
  mutate(group = ifelse((subID %in% controls), "control", "psychoeducation")) %>%
  filter(!subID=="5ed7a0239e6b4a23ec6eb236") %>%
  ggplot(aes(x=catchQsCorrect, fill=group, group=group)) +
  geom_bar(alpha=.6, position = "dodge") + 
  theme_minimal() + xlab("both self-report catch correct?") + theme(legend.position = "none") #+
  #scale_fill_manual(values=wes_palette(n=2, name="GrandBudapest2"))

((p1 + p2 ) / ( p3 + p4 ))

(p1 + p2 + p3 + p8)
```