---
title: "modComp study planning intervention model-based analysis of reward-effort decision-making task"
output:
  html_document:
    html-math-method:
      method: mathjax
  #  pdf_document:
  # extra_dependencies: ["bbm"]
  # fig_caption: yes
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo=FALSE, error=TRUE, warning=FALSE, message=FALSE, fig.align='center')

# load packages
packages <- c("rstan", "dplyr", "tidyr", "bayesplot", "loo", "hBayesDM", "tidybayes", "forcats",
              "ggpmisc", "patchwork", "devtools", "reshape2", "ggExtra", "unikn", "svglite",
              "lme4", "glmnet", "ggcorrplot")
if (length(setdiff(packages, rownames(installed.packages()))) > 0 ) {
  install.packages(setdiff(packages, rownames(installed.packages())))
}
lapply(packages, require, character.only=TRUE)

# set wd
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
# what task version to filter for
task_ver <- "rew-eff-planning-1"    #rew-eff-plannning-2
# create figures subdir
subdir <- "figures"
if (!file.exists(subdir)){
  dir.create(file.path(dirname(rstudioapi::getActiveDocumentContext()$path), subdir))
}
```

```{r setup_rstan}
rstan_options(auto_write = TRUE)   # write the models so we don't have to recompile each time
nCores <- parallel::detectCores()    # get number of cores available for parallelisation
```

```{r setup_colour_scales}
# lets set some custom colour scales for our plots using unikn
seecol(pal_unikn_pair)
palette2 <- usecol(pal_unikn_pair)
# colours by intervention group
colours3 <- c("planning" = palette2[11],
              "control" = palette2[10]              # planning intervention control
              # "psychoed" = palette2[1],
              # "control" = palette2[2]             # psychoed intervention control
              )
# colours by model parameter type
colours2 <- c("group mean" = palette2[14],
              "intervention effect" = palette2[11]
              )
```

```{r load_data}
# load long format data
data_long_all <- read.csv(file=paste0("./", task_ver, "-task-data-long.csv")) %>%
  dplyr::select(-X) %>%
  arrange(subID, taskNo, trialNo) %>%
  mutate(sess = taskNo,
         condition = group,
         choice01=recode(choice, "route 1"=0, "route 2"=1))

## get number of time points etc
nPpts <- length(unique(data_long_all$subID))
nTimes <- max(data_long_all$sess)
nTrials_all <- data_long_all %>%
  group_by(subID, sess) %>%
  summarize(nTrials = n())

# get lists of subjects IDs by condition for use with other data
control_subs <- data_long_all %>%
  filter(condition=="control") %>%
  dplyr::select(subID, ID)
controls <- as.list(unique(control_subs$subID))
control_IDs <- as.list(unique(control_subs$ID))

# get ordered list of intervention conditions
int_conds <- data_long_all %>%
  arrange(ID) %>%
  group_by(ID) %>%
  dplyr::select(ID, condition) %>%
  distinct() %>%
  mutate(condition01 = ifelse(condition=="planning", 1, 0))
```


```{r stan_format_data}
## create arrays of choice options and responses for each participant and time point
r1 <- e1 <- r2 <- e2 <- choice01 <- array(0, dim = c(nPpts, nTimes, nTrials_max))
nT_ppts <- array(nTrials_max, dim = c(nPpts, nTimes))
for (i in 1:nPpts) {
  for (t in 1:nTimes) {
  r1[i,t,] <- with(data_long_all, trialReward1[ID==i & sess==t])
  e1[i,t,] <- with(data_long_all, trialEffortPropMax1[ID==i & sess==t])
  r2[i,t,] <- with(data_long_all, trialReward2[ID==i & sess==t])
  e2[i,t,] <- with(data_long_all, trialEffortPropMax2[ID==i & sess==t])
  choice01[i,t,] <- with(data_long_all, choice01[ID==i & sess==t]) 
  }
}

## create list to pass to stan
data_list <- list(
  nPpts = nPpts,                 # number of participants
  nTimes = nTimes,               # number of times each participant completed the task
  condition = int_conds$condition01,  # intervention condition for each participant
  nTrials_max = nTrials_max,     # max number of trials per participant
  nT_ppts = nT_ppts,             # actual number of trials per participant
  rew1 = r1,                     # reward level for left option 
  eff1 = e1,                     # effort level for left balloon 
  rew2 = r2,                     # reward level for right option 
  eff2 = e2,                     # effort level for right option
  choice01 = choice01            # chosen option ([0,1]=[left,right]), for bernoulli logit
)
```

### Models with an additive factor of intervention

```{r stan_int_models}
## specify full model name and list of parameters to save in output (otherwise big)
model <- "rewEff-linear-bernoulli-multisess-intervention-additive"
params_to_save <- c("rewSens", "effSens", "mu_rewSens", "mu_effSens", "sigma_rewSens", "sigma_effSens",
                    "sum_log_lik", "rewSens_int", "effSens_int", "y_rep", "R_rewSens", "R_effSens")

## fit model using rstan
fit <- stan(
  file = paste0("./stan-models/", model, ".stan"),
  data = data_list,
  pars = params_to_save,
  include = TRUE,         # only save the listed parameters, not other intermediates
  chains = 4,               # run 4 separate chains to assess convergence
  warmup = 1000,            # these are used to tune the sampler and ’burn in’
  iter = 2000,              # number of iterations (#kept = chains*(iter - warmup))
  cores = nCores            # chains to be run in parallel on separate cores (if possible)
)

## save
saveRDS(fit, file = paste0("./stan-fits/", model, "-", task_ver, "-fit.rds"))

# summary of sampling diagnostics
check_hmc_diagnostics(fit)

# plot pairs of sampling distributions for an example participant
pairs(fit, pars=c("rewSens[1,1]", "rewSens[2,1]", "effSens[1,1]", "effSens[2,1]"))

# plot pairs of sampling distributions for th group level means
pairs(fit, pars=c("mu_rewSens[1]", "mu_rewSens[2]", "mu_effSens[1]", "mu_effSens[2]"))
 
# plot intervention and individual t2 a[irs ]
pairs(fit, pars=c("rewSens_int", "effSens_int"))
```

```{r test_retest_bothsess_plot}
# specify and load model 
fit <- readRDS(file = paste0("./stan-fits/", model , "-", task_ver, "-fit.rds"))
  
# test-retest posteriors
R_theta_neg <- as.data.frame(summary(fit, pars = c("R_rewSens"))$summary)
R_theta_pos <- as.data.frame(summary(fit, pars = c("R_effSens"))$summary)
# print mean and mean se for each parameter
print(paste0("test-retest R for rewSens (mean): ", round(R_theta_neg$mean[2],2)), quote=FALSE)
print(paste0("test-retest R for rewSens (SE of mean): ", round(R_theta_neg$se_mean[2],3)), quote=FALSE)

print(paste0("test-retest R for effSens (mean): ", round(R_theta_pos$mean[2],2)), quote=FALSE)
print(paste0("test-retest R for effSens (SE of mean): ", round(R_theta_pos$se_mean[2],3)), quote=FALSE)

# get posterior param estimates from session 1 vs 2
posts <- as.data.frame(summary(fit, pars = c("rewSens", "effSens"))$summary) %>%
  dplyr::select(mean, sd) %>%
  add_rownames(var = "var") %>%
  separate(var, sep="\\[|\\,|\\]", into=c("parameter", "ID", "session"), 
           remove=TRUE, extra="drop")

## plot
p1 <- posts %>%
  pivot_wider(id_cols=c("ID", "parameter"), names_from = "session", 
              values_from = c("mean", "sd")) %>%
  mutate(condition = ifelse(ID %in% control_IDs, "control", "planning")) %>%
  ggplot(aes(x=mean_1, y=mean_2, group=condition, colour=condition)) +
  geom_abline(slope = 1, linetype="dashed", colour="grey") +
  geom_smooth(method = "lm", se=FALSE, formula = y ~ x) +
  geom_point() +
  geom_errorbarh(aes(xmin = mean_1-sd_1, xmax = mean_1+sd_1), alpha=.4) + 
  geom_errorbar(aes(ymin = mean_2-sd_2, ymax = mean_2+sd_2), alpha=.4) +
  scale_colour_manual(values=colours3) + 
  scale_fill_manual(values=colours3) +
  labs(x = "mean (sd) time 1", y ="mean (sd) time 2") + 
  theme_minimal() + facet_wrap(~parameter) + labs() + theme(aspect.ratio=4/3)
print(p1)
# ggsave(filename = paste0("./figures/", task_ver, "-params-by-time.svg"),
#        plot = last_plot(), device = "svg", dpi = 300)

p1 <- posts %>%
  pivot_wider(id_cols=c("ID", "session"), names_from = "parameter", 
              values_from = c("mean", "sd")) %>%
  ggplot(aes(x=mean_rewSens, y=mean_effSens))  +
  geom_smooth(method = "lm", se=TRUE, alpha=.2, color="black", formula = y ~ x) +
  geom_point() +
  geom_errorbarh(aes(xmin = mean_rewSens-sd_rewSens, xmax = mean_rewSens+sd_rewSens), alpha=.2) + 
  geom_errorbar(aes(ymin = mean_effSens-sd_effSens, ymax = mean_effSens+sd_effSens), alpha=.2) +
  xlab("posterior mean reward sensitivity") + ylab("posterior mean effort sensitivity") +
  theme_minimal() + theme(strip.text = element_text(face = "bold", size=12)) + facet_wrap(~session)
print(p1)

# visualize differences in posterior group means between timepoints and posterior estimates of intervention effects using tidybayes package (quick and pretty!)
fit_tidy <- fit %>% 
  gather_draws(`mu_effSens[1]`, `mu_effSens[2]`, `mu_rewSens[1]`, `mu_rewSens[2]`,
               effSens_int, rewSens_int) %>%
  mutate(var_type = ifelse(grepl("int", .variable), "intervention effect", "group mean"),
         var_type = factor(var_type, levels = c("group mean", "intervention effect")),
         .variable = factor(.variable, levels = c("mu_effSens[1]", "mu_effSens[2]",
                                                  "mu_rewSens[1]", "mu_rewSens[2]",
                                                   "effSens_int", "rewSens_int")))
p <- fit_tidy %>%
  ggplot(aes(y = fct_rev(.variable), x = .value, fill = var_type)) +
  stat_gradientinterval(.width = c(.9, .5),  slab_size = 1) +
  scale_fill_manual(values = colours2) +
  geom_vline(xintercept = 0, colour = "grey") + theme_minimal() +
  theme(legend.position = "none") + theme(aspect.ratio=4/3) + labs(x="", y="")
p
# ggsave(filename = paste0("./figures/", task_ver, "-means-ints-CIs-gradient.svg"),
#        plot = last_plot(), device = "svg", dpi = 300)

# print numerical values for 90% credible intervals (quantile-based)
params90cis <- summary(fit, pars = c("mu_effSens[1]", "mu_effSens[2]",
                                     "mu_rewSens[1]", "mu_rewSens[2]",
                                     "rewSens_int", "effSens_int"), probs = c(0.05, 0.95))$summary
print(params90cis)
```

```{r post_pred_acc}
# original data
y <- data_long_all$choice01

# extract replicate data generated using posterior parameter estimates
y_rep <- as.data.frame(summary(fit, pars = c("y_rep"))$summary) %>%
  filter(mean>=0) %>%   # remove padded values for trials ppts didn't actually complete
  dplyr::select(`50%`) %>%
  add_rownames(var = "var") %>%
  separate(var, sep="\\[", into=c("variable","tmp"), remove=TRUE, extra="drop") %>%
  separate(tmp, sep=",", into=c("subID","trial"), remove=TRUE, extra="drop") %>%
  separate(trial, sep=-1, into="trial", extra="drop") %>%
  mutate(subID=as.numeric(subID)) %>%
  arrange(subID) %>%
  rename(mean_predicted = `50%`)

# predictive accuracy (per sub)
y_rep <- cbind(y_rep, observed=y)
accs <- y_rep %>%
  group_by(subID) %>%
  mutate(acc = (mean_predicted==observed)) %>%
  summarise(mean_acc = mean(acc))

# predictive accuracy (overall)
summ <- accs %>%
  summarise(mean_pred_acc=round(mean(mean_acc),2), sd_pred_acc=round(sd(mean_acc),2))
print(summ)

# sum log lik for each participant
sum_log_liks <- rstan::extract(fit, pars = "sum_log_lik")[[1]]
mean_sum_log_liks <- colMeans(sum_log_liks) # average over samples

# pseudo r2
# pseudo-r2 can be calculated as 1 - L/C where L = sumloglik over participants and C = likelihood of observing by chance (nTrials*log(0.5))
pseudo_r2 = 1 - (mean_sum_log_liks/nTrials_max*log(0.5))
print(mean(pseudo_r2)); print(sd(pseudo_r2))
```


```{r plot_posteriors}
# plot posterior densities for key parameters
a <- plot(fit, pars = "rewSens", ci_level = 0.5, fill_color = "sky blue") +
  ggtitle("posterior rewSens (0.5, 0.95 CI)") +
  theme(axis.text.y=element_blank(), plot.title=element_text(size = 12, face = "bold", hjust = 0.5))
  
b <- plot(fit, pars = "effSens", ci_level = 0.5, fill_color = "dark blue") +
  ggtitle("posterior effSens (0.5, 0.95 CI)") +
  theme(axis.text.y=element_blank(), plot.title=element_text(size = 12, face = "bold", hjust = 0.5))
(a + b)
```


```{r sim_recov}
# reformat extracted choices
y_rep$trial <- as.numeric(y_rep$trial)
choice_rep <- array(0, dim = c(nPpts, nTimes, nTrials_max))
for (i in 1:nPpts) {
  choice_rep[i,1,] <- with(y_rep, as.integer(mean_predicted[subID==i & trial<=44]))
  choice_rep[i,2,] <- with(y_rep, as.integer(mean_predicted[subID==i & trial>44]))
}
data_list$choice01 <- choice_rep

## fit model using rstan
fit_rep <- stan(
  file = paste0("./stan-models/", model, ".stan"),
  data = data_list,
  pars = params_to_save,
  include = TRUE,           # only save the listed parameters, not other intermediates
  chains = 4,               # run 4 separate chains to assess convergence
  warmup = 1000,            # these are used to tune the sampler and ’burn in’
  iter = 2000,              # number of iterations (#kept = chains*(iter - warmup))
  cores = nCores            # chains to be run in parallel on separate cores (if possible)
)

# save
saveRDS(fit_rep, file = paste0("./stan-fits/", model, "-", task_ver, "-fit-rep.rds"))

# load both original fit and fit to replicate daa
fit <- readRDS(file=paste0("./stan-fits/", model, "-",  task_ver, "-fit.rds"))
fit_rep <- readRDS(file=paste0("./stan-fits/", model, "-", task_ver, "-fit-rep.rds"))

# plot original posterior vs replicated data posterior means/SDs
params = c("rewSens", "effSens")
posts <- as.data.frame(summary(fit, pars=params)$summary) %>%
  dplyr::select(mean,sd) %>%
  add_rownames(var = "var") %>%
  separate(var, sep="\\[", into=c("parameter", "subID"), remove=TRUE, extra="drop") %>%
  separate(subID, sep=",", into=c("subID", "session")) %>%
  separate(session, sep=-1, into="session", extra="drop")

posts_rep <- as.data.frame(summary(fit_rep, pars=params)$summary) %>%
  dplyr::select(mean,sd) %>%
  add_rownames(var = "var") %>%
  separate(var, sep="\\[", into=c("parameter", "subID"), remove=TRUE, extra="drop") %>%
  separate(subID, sep=",", into=c("subID", "session")) %>%
  separate(session, sep=-1, into="session", extra="drop")

posts_both <- merge(posts, posts_rep, by=c("subID", "parameter", "session"), no.dups = TRUE) %>%
  rename("mean" = mean.x, "mean_rep"= mean.y,
         "sd" = sd.x, "sd_rep" = sd.y)
posts_both$parameter <- factor(posts_both$parameter, levels = params)  #reorder
p <- ggplot(posts_both, aes(x=mean, y=mean_rep)) +
  geom_abline(slope = 1, linetype="dashed", colour="grey") +
  geom_point() +
  geom_errorbarh(aes(xmin = mean-sd, xmax = mean+sd), alpha=.2) + 
  geom_errorbar(aes(ymin = mean_rep-sd_rep, ymax = mean_rep+sd_rep), alpha=.2) +
  xlab("posterior mean (sd)") + ylab("posterior mean (sd) recovered from replicated data") +
  stat_poly_eq(formula = y~x, label.x = "right", label.y = "bottom",
                 aes(label = paste(stat(rr.label), stat(p.value.label), sep = "~~~")),
                 parse = TRUE) +
  theme_minimal() + theme(strip.text = element_text(face = "bold", size=12)) +
  facet_grid(cols= vars(session), rows = vars(parameter)) #facet_wrap(~parameter, scales = "free") #+ ylim(0,1.1) + xlim(0,1.1)
p
```

